[package]
name = "yew-vdom-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
web-sys = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3"
gloo-utils = "0.1.0"
gloo-console = "0.2.0"
